table 'Netflix (3)'
	lineageTag: 4008e035-ad8e-47d1-9010-d96a5b01a776

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 33c8f3c7-c8f0-4757-8f23-31499c2e7fb9
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: d7432d68-be4b-4d6a-a1ad-2c5a48a8cf5d
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: 12821426-fbcb-4578-8bb3-1c8c3dfec523
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column Director
		dataType: string
		lineageTag: 6cba749f-9b64-4110-b2c2-15ba365a5cb3
		summarizeBy: none
		sourceColumn: Director

		annotation SummarizationSetBy = Automatic

	column Cast
		dataType: string
		lineageTag: 1df20d44-b16b-45da-b572-d52d74a05a4f
		summarizeBy: none
		sourceColumn: Cast

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: eb274ea5-b158-4b37-be90-ff4f9bf565c1
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'Date Added'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 66dad6c6-e5fe-482e-b81b-ebeae7946312
		summarizeBy: none
		sourceColumn: Date Added

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Release Year'
		dataType: int64
		formatString: 0
		lineageTag: 506cf332-340c-4647-b436-bec87a328aa7
		summarizeBy: none
		sourceColumn: Release Year

		annotation SummarizationSetBy = Automatic

	column Rating
		dataType: string
		lineageTag: 8b096cc1-a526-4b83-b944-606015c16ad3
		summarizeBy: none
		sourceColumn: Rating

		annotation SummarizationSetBy = Automatic

	column Duration
		dataType: string
		lineageTag: 18c79a01-860a-4d79-bccc-915dbd55393c
		summarizeBy: none
		sourceColumn: Duration

		annotation SummarizationSetBy = Automatic

	column Genre
		dataType: string
		lineageTag: eb36e766-a5a6-4c53-ae0c-41c9bbda2f95
		summarizeBy: none
		sourceColumn: Genre

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 2a819f7c-4b69-49e9-bbd2-22b82ce66e63
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition 'Netflix (3)-4cf0a00f-d4d9-42e2-93a4-08f05c95e3e7' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Git\PowerBi\Netflix Dashboard\netflix_titles.csv"),[Delimiter=",", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"show_id", type text}, {"type", type text}, {"title", type text}, {"director", type text}, {"cast", type text}, {"country", type text}, {"date_added", type date}, {"release_year", Int64.Type}, {"rating", type text}, {"duration", type text}, {"listed_in", type text}, {"description", type text}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Changed Type",{{"cast", Text.Trim, type text}}),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Trimmed Text", {{"date_added", type date}}, "en-GB"),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type with Locale", {"date_added"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Errors","s","",Replacer.ReplaceText,{"show_id"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value",{{"show_id", Int64.Type}}),
				    #"Removed Errors1" = Table.RemoveRowsWithErrors(#"Changed Type2", {"show_id"}),
				    #"Trimmed Text1" = Table.TransformColumns(#"Removed Errors1",{{"listed_in", Text.Trim, type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Trimmed Text1",{{"show_id", "ID"}, {"type", "Type"}, {"title", "Title"}, {"director", "Director"}, {"cast", "Cast"}, {"country", "Country"}, {"date_added", "Date Added"}, {"release_year", "Release Year"}, {"rating", "Rating"}, {"duration", "Duration"}, {"description", "Description"}, {"listed_in", "Genre"}}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Renamed Columns", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Blank Rows", each ([Rating] <> "66 min" and [Rating] <> "74 min" and [Rating] <> "84 min")),
				    #"Trimmed Text2" = Table.TransformColumns(#"Filtered Rows",{{"Country", Text.Trim, type text}})
				in
				    #"Trimmed Text2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

